### ISSUE TITLE
Service Startup docs

### ISSUE THREAD

**Issue by gregwkeller** [ctrliq/warewulf#11]
This syntax appears to be obsolete...
"sudo ./wwctl service -a"

It may be replaced by...
"sudo ./wwctl server start"

Please update the Readme/Docs

e.g.
[greg@controller7 warewulf]$ sudo ./wwctl server status
[INFO]     Warewulf daemon process not running (/tmp/warewulfd.pid)
[greg@controller7 warewulf]$ sudo ./wwctl server start
Warewulf daemon is running at PID: 14962
[greg@controller7 warewulf]$ sudo ./wwctl server status
Warewulf daemon is running at PID: 14962

**Comment by gregwkeller** [comment]
I think the command was intended to be...
"sudo ./wwctl configure -a"

**Comment by gmkurtzer** [comment]
@gregwkeller There is both the `wwctl service` command as well as the `wwctl configure` command. I think it is correct now, can you confirm?

**Comment by gregwkeller** [comment]
service is not a command....

amelia@Amelia7:~/warewulf$ sudo ./wwctl service help
Error: unknown command "service" for "wwctl"
Run 'wwctl --help' for usage.


amelia@Amelia7:~/warewulf$ sudo ./wwctl configure help                                         
Warewulf Service Initialization

Usage:
  wwctl configure [flags]
  wwctl configure [command]

Available Commands:
  dhcp        DHCP configuration
  hosts       NFS configuration
  nfs         NFS configuration
  ssh         SSH configuration
  tftp        TFTP configuration

Flags:
  -a, --all    Configure all services
  -h, --help   help for configure

Global Flags:
  -d, --debug     Run with debugging messages enabled.
  -v, --verbose   Run with increased verbosity.

Use "wwctl configure [command] --help" for more information about a command.

**Comment by brianclemens** [comment]
Documentation now reflects service startup via `wwctl server start`.
