### ISSUE TITLE
--kernelargs or -A sets the kernel, not the args

### ISSUE THREAD

**Issue by jlinford** [ctrliq/warewulf#30]
Ouch!  Trying to set the kernel arguments sets the kernel image.
```
wwctl profile set default --kernelargs="noquiet init=/init crashkernel=no rootfstype=tmpfs"

# wwctl profile list default
################################################################################
PROFILE NAME         FIELD              VALUE
default              Id                 default
default              Comment            This profile is automatically included for each node
default              ClusterName        --
default              ContainerName      centos
default              KernelVersion      noquiet init=/init crashkernel=no rootfstype=tmpfs
default              KernelArgs         --
default              Init               --
default              Root               --
default              RuntimeOverlay     --
default              SystemOverlay      --
default              Ipxe               --
default              IpmiIpaddr         --
default              IpmiNetmask        --
default              IpmiGateway        --
default              IpmiUserName       --
```

**Comment by jlinford** [comment]
So now that I've goofed up my kernel version, how do I unset it back to the default?

**Comment by jlinford** [comment]
And, when prompting the user to confirm the change, it would be good to see what the profile will look like after the change:

`[root@com-1-1 4.14.0-49.el7a.aarch64]# wwctl profile set default -A="noquiet init=/init crashkernel=no rootfstype=tmpfs"
? Are you sure you want to modify 1 profile(s)? [y/N] █`
(I'd like to see a `profile list default` with proposed changes here)

**Comment by jlinford** [comment]
Ya, this also happens with `-A` instead of `--kernelargs`

**Comment by gmkurtzer** [comment]
The primary bug here has been fixed, thank you for finding and reporting it!

The secondary feature request hasn't been done yet.
