### ISSUE TITLE
--debug and --verbose are mutually exclusive

### ISSUE THREAD

**Issue by rhenwood-arm** [ctrliq/warewulf#36]
While playing with container import, It seems --debug and --verbose are mutually exclusive:
```
[root@localhost ~]# wwctl container import docker://warewulf/centos-8 centos-8 --debug
[DEBUG]    12:18:58.271320 Set log level to: 5
[WARN]     12:18:58.271588 VNFS name has illegal characters: centos-8
[ERROR]           12:18:58.271596 VNFS name contains illegal characters: centos-8
[root@localhost ~]# wwctl container import docker://warewulf/centos-8 centos-8 --debug --verbose
[WARN]     VNFS name has illegal characters: centos-8
[ERROR]           VNFS name contains illegal characters: centos-8
```

I don't believe they need to be from a tooling and UI perspective.

It appears to be the code in [./wwwctl/root.go](https://github.com/ctrliq/warewulf/blob/e7b7414b8f2b6813b1dae212095f2300217c208e/internal/app/wwctl/root.go#L53) that makes that decision.

**Comment by gmkurtzer** [comment]
This should be fixed now. Thank you!
